# Generated by Django 4.2.5 on 2023-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='mac_address',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='nin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votebackup',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='votebackup',
            name='mac_address',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='votebackup',
            name='nin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
