# Generated by Django 4.2.5 on 2023-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_vote_ip_address_vote_mac_address_vote_nin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='inec',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votebackup',
            name='inec',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
