# Generated by Django 4.2.5 on 2023-10-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_vote_inec_votebackup_inec'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='votebackup',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
