# Generated by Django 4.2.5 on 2023-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_vote_state_votebackup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='votebackup',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
