# Generated by Django 4.2.5 on 2023-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_alter_block_timestamp_alter_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='votebackup',
            name='vote',
            field=models.CharField(max_length=5),
        ),
    ]
