# Generated by Django 4.2.5 on 2023-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_alter_vote_vote_alter_votebackup_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='votebackup',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
